### ISSUE TITLE
Make a matrix of specimens/taxa and markers

### ISSUE THREAD

**Issue by tle003** [tle003/Schoenus-phylogeny#1]
To be used for both phylogeny 1 & 2.

**Comment by tle003** [comment]
Phylogeny 1: Schoenus within Schoeneae with a couple outgroups (Carphae)
- reassert monophylly of Schoenus within Schoeneae
- evaluate monophylly of Cape Schoenus within Schoenus
- eventually do some ancestoral area reconstruction

**Comment by tle003** [comment]
Task #1
- Ruan and Tammy make a matrix of specimens/taxa and markers

**Comment by tle003** [comment]
I have make a summary list of the sequences that I currently have for 391 Schoeneae species. 

I think that I should now see how many of these I can find rbcL sequences for.

**Comment by rvanmazijk** [comment]
Judging from the response we got to Muthama's email to our potential Australian collaborators, we will need to (eventually) integrate their data into this matrix. The urgency of that depends on the ultimate scope of the paper, though.

**Comment by rvanmazijk** [comment]
> Judging from the response we got to Muthama's email to our potential Australian collaborators, we will need to (eventually) integrate their data into this matrix. The urgency of that depends on the ultimate scope of the paper, though.

Also, I have spoken to Muthama about a possible discussion between him, Tammy and me about the scope of the paper.

**Comment by tle003** [comment]
I think that we already have markers for 80-90 % of Schoenus species, so any data they would provide would be additional markers for species/specimens that we already have. This would be great!

**Comment by tle003** [comment]
I think that the best time for a meeting would be when we have an idea of what we have for sequences. Then, we can propose our ideas of how to go forward with the two phylogenies.

**Comment by tle003** [comment]
Tammy's numbers with rbcL: 

 ETS  ITS rbcL  rps  trn 
 112  194  160   55  145 

This is from approximately 469 different specimens, with 128 specimens with > 1 different marker.

**Comment by rvanmazijk** [comment]
I have added the specimens I have sequence data for into Tammy’s spreadsheet where needed and have summarised the sequence availability at the taxon-level.

As far as I can tell, that leaves us with:
- 468 specimens sequenced,  160 of which have > 1 marker
- representing ca. 239 taxa, 130 of which have > 1 marker
