### ISSUE TITLE
Read D. Spalink Caricae paper(s)

### ISSUE THREAD

**Issue by rvanmazijk** [tle003/Schoenus-phylogeny#2]
From the last couple of years.

Muthama mentioned that they use some interesting analyses.

**Comment by tle003** [comment]
[Spalink et al. - 2018 - The spatial structure of phylogenetic and function.pdf](https://github.com/tle003/Schoenus-phylogeny/files/4430557/Spalink.et.al.-.2018.-.The.spatial.structure.of.phylogenetic.and.function.pdf)
[Spalink et al. - 2016 - Biogeography of the cosmopolitan sedges (Cyperacea.pdf](https://github.com/tle003/Schoenus-phylogeny/files/4430558/Spalink.et.al.-.2016.-.Biogeography.of.the.cosmopolitan.sedges.Cyperacea.pdf)
[Spalink et al. - 2016 - Evolution of geographical place and niche space P.pdf](https://github.com/tle003/Schoenus-phylogeny/files/4430559/Spalink.et.al.-.2016.-.Evolution.of.geographical.place.and.niche.space.P.pdf)


 I found three papers from Daniel Spalink that Muthama might have been referring to. I took a brief look at them this evening and will look at them tomorrow. There are a couple of analyses that could be adapted for our work, but I think that we would have to use more current methods and approaches (especially with regards to the 2016 papers).

**Comment by tle003** [comment]
Spalink et al. 2016 - **Evolution of geographical place and niche space (Carex)**

Some ideas: we could do a similar visualization showing _Schoenus_ richness per grid cell
- we have the data for the Southern African _Schoenus_
- I recommend searching out a better method to create the visualization
- speciation through time is possible with our data set (I think). We could look at this with different characters and do the BAMM analyses, such as in this paper, but I don't know if we would find anything interesting

I did not find the PGLS nor species tree/geography tree visualizations very informative. I think that if we want to compare the ranges for different _Schoenus_ species in an evolutionary context, a different method would probably be more suitable for our data and questions.

**Comment by tle003** [comment]
Spalink et al. 2018 - **The spatial structure of phylogenetic and functional diversity in the United States and Canada: An example using the sedge family (Cyperaceae))**

Some ideas: there are some more analyses/visualizations that we can consider:
- create visualizations by major clade (each clade has its own colour); plot to QDGC
- in addition to species richness, we could also plot Faith's phylogenetic diversity (FPD),  mean phylogenetic distance (MPD) and functional diversity. If we can include the Australian taxa, they would have a higher Faith's and MPD
- significant departure from expectations can also be calculated from the above
- can look at correlates of alpha diversity (modified t-test); are the species richness variables correlated within themselves? Are they correlated with functional diversity variables?
- we have the characters to calculate functional diversity (at least for the Southern African _Schoenus_)
- spatial patterns of functional traits
    - I think that this would be interesting
   - we could look into this using a different set of analyses

**Predictions:**

- Given that most sedge species occur in wetlands and that Arctic habitats are generally species depauperate, species richness should increase with both temperature and precipitation; 
- Phylogenetic diversity should peak in the subtropical USA, where the merger of temperate and tropical lineages is likely to be most concentrated; 
- Phylogenetic turnover should increase more strongly with distance along latitudinal than longitudinal gradients, but floristic turnover should increase approximately equally along both gradients

**Comment by tle003** [comment]
Spalink et al. 2016 - **Biogeography of the cosmopolitan sedges (Cyperaceae) and the area‐richness correlation in plants**

Some key points about the analyses:
- they used a BAMM analysis for the diversification rates
- BioGeoBEARS was used for the ancestoral area reconstruction.
- I liked the figure for the ancestoral area reconstruction more than Viljoen et al. 2013
     - Spalink et al. had separate columns for each major geographical area so it looks neater
- used PGLS with clade richness, clade range and diversification rates as response variables. Different Predictors included diversification rate, clade richness, average species range, etc.

Hypotheses: 
- Clades occurring over large geographical and ecological extents are more diverse than spatially and ecologically restricted clades
- clade richness and diversification rate increase with the ratio of the average species range within a clade to the clade's overall range

**Comment by rvanmazijk** [comment]
> Spalink et al. 2016 - **Evolution of geographical place and niche space (Carex)**
> 
> Some ideas: we could do a similar visualization showing _Schoenus_ richness per grid cell
> 
> * we have the data for the Southern African _Schoenus_
> * I recommend searching out a better method to create the visualization
> * speciation through time is possible with our data set (I think). We could look at this with different characters and do the BAMM analyses, such as in this paper, but I don't know if we would find anything interesting
> 
> I did not find the PGLS nor species tree/geography tree visualizations very informative. I think that if we want to compare the ranges for different _Schoenus_ species in an evolutionary context, a different method would probably be more suitable for our data and questions.

We discussed this paper in a recent journal club. I (and the rest of the journal club, likely) agree that the PGLS things they did was not particularly insightful. Their range/habitat data, also, makes sense for wider-ranging North American species, but not necessarily for ours.
