### ISSUE TITLE
Previous reconstructions (for reference)

### ISSUE THREAD

**Issue by tle003** [tle003/Schoenus-phylogeny#3]
- [Tammy's](http://northernbotanist.com/Schoeneae-Sangor-phylogenies-prelim/)
- [Ruan's](https://drive.google.com/open?id=1hi8YwUPufkvCTX0dgVFQj3oNce0UQp2u)
    - note: focuses on Cape _Schoenus_ and _Tetraria_ species for Ruan's MSc
    - [details](https://drive.google.com/open?id=112mox5V_SHqetozkK_qqudu_E_5KGQTg)

**Comment by tle003** [comment]
I am not sure if we need to focus too much on the Tetraria species. I think that including Tetraria as part of the Tricostularia is important, but I don't think that we need a full sampling as we are focussing on a Schoenus paper.

Maybe sequences for 5 Tetraria species would be enough?

**Comment by rvanmazijk** [comment]
Of course, I agree. I was just listing these here for reference/posterity.
